export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const SIGN_OUT_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_OUT_ERROR = "SIGN_UP_ERROR";

export const FRIENDS_LOADING = "FRIENDS_LOADING";
export const FRIENDS_LOADED_SUCCESS = "FRIENDS_LOADED_SUCCESS";
export const FRIENDS_LOADED_FAILED = "FRIENDS_LOADED_FAILED";
export const FRIEND_STATUS_CHANGE = "FRIEND_STATUS_CHANGE";

export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_ERROR = "GET_NOTIFICATIONS_ERROR";

export const SET_NOTIFICATION_INVITATIONS = "SET_NOTIFICATION_INVITATIONS";
export const SET_NOTIFICATION_BELL = "SET_NOTIFICATION_BELL";
export const SET_NOTIFICATION_MESSAGES = "SET_NOTIFICATION_MESSAGES";
export const SET_NOTIFICATION_ERROR = "SET_NOTIFICATION_ERROR";
